### ISSUE TITLE
Networkit version 7.1 is not installing 

### ISSUE THREAD

**Issue by GaroBozadjian** [networkit/networkit#1005]
I tried to install Networkit version 7.1 with pip install networkit==7.1 it give me this error:

Collecting networkit==7.1
  Using cached networkit-7.1.tar.gz (3.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_pjh6d6w/networkit_469fae510d7748608862faaf7f026975/setup.py", line 7, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

My OS is the latest Ubuntu

**Comment by angriman** [comment]
It seems that you do not have Cython installed. You can install it with pip.

**Comment by GaroBozadjian** [comment]
@angriman  
Thanks for the tip but I installed that cython and cmake but it gives me this error after it reach 20%:

[ 20%] Building CXX object CMakeFiles/networkit.dir/networkit/cpp/centrality/EigenvectorCentrality.cpp.o
      [ 20%] Building CXX object CMakeFiles/networkit.dir/networkit/cpp/centrality/EstimateBetweenness.cpp.o
      make[2]: *** [CMakeFiles/networkit.dir/build.make:454: CMakeFiles/networkit.dir/networkit/cpp/centrality/DynTopHarmonicCloseness.cpp.o] Error 1
      make[2]: *** Waiting for unfinished jobs....
      make[1]: *** [CMakeFiles/Makefile2:1169: CMakeFiles/networkit.dir/all] Error 2
      make: *** [Makefile:136: all] Error 2
      Build tool returned an error, exiting setup.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> networkit

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by fabratu** [comment]
Hm, never stumbled upon your `legacy-install-failure` error before. Seems that most of the time it is related more to the Python/pip environment. Did you already try to upgrade pip (e.g. `pip3 install --upgrade pip` + `pip install - upgrade setuptools`?

I guess you use v7.1 on purpose, but just in case: Since version v9.1 we also distribute NetworKit as a wheel package, which means there is no need for compiling the package on most systems.

**Comment by GaroBozadjian** [comment]
@fabratu 
Thanks for the tip, but i tried it already there is no luck.
it give me the same error.

**Comment by fabratu** [comment]
Alright - can you give more information about the environment you are using (like OS, `pip freeze`, default c++ compiler version)?

**Comment by GaroBozadjian** [comment]
@fabratu 
my OS it is the latest Ubunto 22.04.1 LTS.
pip freeze:
astor==0.8.1
autograd==1.5
autograd-gamma==0.5.0
beautifulsoup4==4.11.1
certifi==2022.9.24
charset-normalizer==2.1.1
contourpy==1.0.6
cycler==0.11.0
Cython==0.29.32
docopt==0.6.2
fonttools==4.38.0
formulaic==0.5.2
future==0.18.2
gensim==4.2.0
idna==3.4
interface-meta==1.3.0
Js2Py==0.71
kiwisolver==1.4.4
lifelines==0.27.3
matplotlib==3.6.2
numpy==1.23.4
packaging==21.3
pandas==1.5.1
Pillow==9.3.0
pipwin==0.5.2
pyjsparser==2.7.1
pyparsing==3.0.9
PyPrind==2.11.3
pySmartDL==1.3.4
python-dateutil==2.8.2
pytz==2022.6
pytz-deprecation-shim==0.1.0.post0
requests==2.28.1
scipy==1.9.3
six==1.16.0
smart-open==6.2.0
soupsieve==2.3.2.post1
typing_extensions==4.4.0
tzdata==2022.6
tzlocal==4.2
urllib3==1.26.12
wrapt==1.14.1

and those are the compilers:
ii  g++                                        4:11.2.0-1ubuntu1                                    amd64        GNU C++ compiler
ii  g++-11                                     11.3.0-1ubuntu1~22.04                                amd64        GNU C++ compiler
ii  gcc                                        4:11.2.0-1ubuntu1                                    amd64        GNU C compiler
ii  gcc-11                                     11.3.0-1ubuntu1~22.04                                amd64        GNU C compiler
ii  gfortran                                   4:11.2.0-1ubuntu1                                    amd64        GNU Fortran 95 compiler
ii  gfortran-11                                11.3.0-1ubuntu1~22.04                                amd64        GNU Fortran compiler
ii  libllvm13:amd64                            1:13.0.1-2ubuntu2.1                                  amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm14:amd64                            1:14.0.0-1ubuntu1                                    amd64        Modular compiler and toolchain technologies, runtime library
ii  libxkbcommon0:amd64                        1.4.0-1                                              amd64        library interface to the XKB compiler - shared library
ii  rpcsvc-proto                               1.4.2-0ubuntu6                                       amd64        RPC protocol compiler and definitions

**Comment by fabratu** [comment]
Thanks for the info. I was able to reproduce your problem. Actually it is likely, that gcc-11 is the problem here. At least on the test machine I get quite some errors from missing C++ standard headers. With older gcc versions (or using clang), certain headers like `<limits>` were automatically added on compilation. gcc-11 made naming those headers explicitly necessary.

Technically we added gcc-11 support with NetworKit 9.0. You can see this for example [here](https://github.com/networkit/networkit/commit/e15362b0f2ee81fb873c89b01613c4b80c207eb6) for the priority queue, used in quite some algorithms throughout the code base.

One easy workaround would be to install gcc-9 (available directly on Ubuntu 22.04):
```
sudo apt-get install gcc-9
```
Note that does not change your default environment or compilers, so that should be easily done. After that you can install NetworKit via:
```
CXX=g++-9 pip3 install networkit==7.1
```

Let me know whether that worked for you.

**Comment by GaroBozadjian** [comment]
@fabratu 
it didn't work with me it gives me this error:
Collecting networkit==7.1
  Using cached networkit-7.1.tar.gz (3.1 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scipy in ./miniconda3/lib/python3.9/site-packages (from networkit==7.1) (1.9.3)
Requirement already satisfied: numpy in ./miniconda3/lib/python3.9/site-packages (from networkit==7.1) (1.23.4)
Building wheels for collected packages: networkit
  Building wheel for networkit (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [78 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/GraphMLIO.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/nxadapter.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/partitioning.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/plot.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/support.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/stopwatch.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/GEXFIO.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/algebraic.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/dynamic.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/exceptions.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/sampling.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/viztasks.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/coloring.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/workflows.py -> build/lib.linux-x86_64-cpython-39/networkit
      creating build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_algorithms.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_generators.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_randomization.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_sparsification.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_graph_traversal.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_graph.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_graphio.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_community.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_graphtools.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      creating build/lib.linux-x86_64-cpython-39/networkit/profiling
      copying networkit/profiling/multiprocessing_helper.py -> build/lib.linux-x86_64-cpython-39/networkit/profiling
      copying networkit/profiling/profiling.py -> build/lib.linux-x86_64-cpython-39/networkit/profiling
      copying networkit/profiling/plot.py -> build/lib.linux-x86_64-cpython-39/networkit/profiling
      copying networkit/profiling/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit/profiling
      copying networkit/profiling/job.py -> build/lib.linux-x86_64-cpython-39/networkit/profiling
      creating build/lib.linux-x86_64-cpython-39/networkit/gephi
      copying networkit/gephi/pyclient.py -> build/lib.linux-x86_64-cpython-39/networkit/gephi
      copying networkit/gephi/streaming.py -> build/lib.linux-x86_64-cpython-39/networkit/gephi
      copying networkit/gephi/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit/gephi
      copying networkit/gephi/csv.py -> build/lib.linux-x86_64-cpython-39/networkit/gephi
      creating build/lib.linux-x86_64-cpython-39/networkit/test/extension
      copying networkit/test/extension/test.py -> build/lib.linux-x86_64-cpython-39/networkit/test/extension
      copying networkit/test/extension/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit/test/extension
      creating build/lib.linux-x86_64-cpython-39/networkit/test/gephi
      copying networkit/test/gephi/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit/test/gephi
      creating build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      copying networkit/profiling/html/profiling.css -> build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      copying networkit/profiling/html/overlay.html -> build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      copying networkit/profiling/html/profiling.js -> build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      copying networkit/profiling/html/profile.html -> build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      copying networkit/profiling/html/measure.html -> build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      creating build/lib.linux-x86_64-cpython-39/networkit/profiling/latex
      copying networkit/profiling/latex/measure.tex -> build/lib.linux-x86_64-cpython-39/networkit/profiling/latex
      copying networkit/profiling/latex/profile.tex -> build/lib.linux-x86_64-cpython-39/networkit/profiling/latex
      creating build/lib.linux-x86_64-cpython-39/networkit/profiling/description
      copying networkit/profiling/description/descriptions.txt -> build/lib.linux-x86_64-cpython-39/networkit/profiling/description
      running build_ext
      initializing NetworKit compilation with: 'cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/pip-install-ney050v8/networkit_6438bc68442d443a8bab03c65be75ee0/build/lib.linux-x86_64-cpython-39 -DCMAKE_CXX_COMPILER=g++-9 -DNETWORKIT_FLATINSTALL=ON -DNETWORKIT_PYTHON=/home/garo/miniconda3/include/python3.9 -DNETWORKIT_PYTHON_SOABI=cpython-39-x86_64-linux-gnu /tmp/pip-install-ney050v8/networkit_6438bc68442d443a8bab03c65be75ee0'
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:2 (project):
        The CMAKE_CXX_COMPILER:
      
          g++-9
      
        is not a full path and was not found in the PATH.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-ney050v8/networkit_6438bc68442d443a8bab03c65be75ee0/build/build_python/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-ney050v8/networkit_6438bc68442d443a8bab03c65be75ee0/build/build_python/CMakeFiles/CMakeError.log".
      cmake returned an error, exiting setup.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for networkit
  Running setup.py clean for networkit
Failed to build networkit
Installing collected packages: networkit
  Attempting uninstall: networkit
    Found existing installation: networkit 10.0
    Uninstalling networkit-10.0:
      Successfully uninstalled networkit-10.0
  Running setup.py install for networkit ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for networkit did not run successfully.
  │ exit code: 1
  ╰─> [79 lines of output]
      running install
      /home/garo/miniconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/GraphMLIO.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/nxadapter.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/partitioning.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/plot.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/support.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/stopwatch.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/GEXFIO.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/algebraic.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/dynamic.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/exceptions.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/sampling.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/viztasks.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/coloring.py -> build/lib.linux-x86_64-cpython-39/networkit
      copying networkit/workflows.py -> build/lib.linux-x86_64-cpython-39/networkit
      creating build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_algorithms.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_generators.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_randomization.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_sparsification.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_graph_traversal.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_graph.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_graphio.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_community.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      copying networkit/test/test_graphtools.py -> build/lib.linux-x86_64-cpython-39/networkit/test
      creating build/lib.linux-x86_64-cpython-39/networkit/profiling
      copying networkit/profiling/multiprocessing_helper.py -> build/lib.linux-x86_64-cpython-39/networkit/profiling
      copying networkit/profiling/profiling.py -> build/lib.linux-x86_64-cpython-39/networkit/profiling
      copying networkit/profiling/plot.py -> build/lib.linux-x86_64-cpython-39/networkit/profiling
      copying networkit/profiling/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit/profiling
      copying networkit/profiling/job.py -> build/lib.linux-x86_64-cpython-39/networkit/profiling
      creating build/lib.linux-x86_64-cpython-39/networkit/gephi
      copying networkit/gephi/pyclient.py -> build/lib.linux-x86_64-cpython-39/networkit/gephi
      copying networkit/gephi/streaming.py -> build/lib.linux-x86_64-cpython-39/networkit/gephi
      copying networkit/gephi/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit/gephi
      copying networkit/gephi/csv.py -> build/lib.linux-x86_64-cpython-39/networkit/gephi
      creating build/lib.linux-x86_64-cpython-39/networkit/test/extension
      copying networkit/test/extension/test.py -> build/lib.linux-x86_64-cpython-39/networkit/test/extension
      copying networkit/test/extension/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit/test/extension
      creating build/lib.linux-x86_64-cpython-39/networkit/test/gephi
      copying networkit/test/gephi/__init__.py -> build/lib.linux-x86_64-cpython-39/networkit/test/gephi
      creating build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      copying networkit/profiling/html/profiling.css -> build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      copying networkit/profiling/html/overlay.html -> build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      copying networkit/profiling/html/profiling.js -> build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      copying networkit/profiling/html/profile.html -> build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      copying networkit/profiling/html/measure.html -> build/lib.linux-x86_64-cpython-39/networkit/profiling/html
      creating build/lib.linux-x86_64-cpython-39/networkit/profiling/latex
      copying networkit/profiling/latex/measure.tex -> build/lib.linux-x86_64-cpython-39/networkit/profiling/latex
      copying networkit/profiling/latex/profile.tex -> build/lib.linux-x86_64-cpython-39/networkit/profiling/latex
      creating build/lib.linux-x86_64-cpython-39/networkit/profiling/description
      copying networkit/profiling/description/descriptions.txt -> build/lib.linux-x86_64-cpython-39/networkit/profiling/description
      running build_ext
      initializing NetworKit compilation with: 'cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/pip-install-ney050v8/networkit_6438bc68442d443a8bab03c65be75ee0/build/lib.linux-x86_64-cpython-39 -DCMAKE_CXX_COMPILER=g++-9 -DNETWORKIT_FLATINSTALL=ON -DNETWORKIT_PYTHON=/home/garo/miniconda3/include/python3.9 -DNETWORKIT_PYTHON_SOABI=cpython-39-x86_64-linux-gnu /tmp/pip-install-ney050v8/networkit_6438bc68442d443a8bab03c65be75ee0'
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:2 (project):
        The CMAKE_CXX_COMPILER:
      
          g++-9
      
        is not a full path and was not found in the PATH.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-ney050v8/networkit_6438bc68442d443a8bab03c65be75ee0/build/build_python/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-ney050v8/networkit_6438bc68442d443a8bab03c65be75ee0/build/build_python/CMakeFiles/CMakeError.log".
      cmake returned an error, exiting setup.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of networkit
  Moving to /home/garo/miniconda3/lib/python3.9/site-packages/include/networkit/
   from /home/garo/miniconda3/lib/python3.9/site-packages/include/~etworkit
  Moving to /home/garo/miniconda3/lib/python3.9/site-packages/include/tlx/
   from /home/garo/miniconda3/lib/python3.9/site-packages/include/~lx
  Moving to /home/garo/miniconda3/lib/python3.9/site-packages/lib/pkgconfig/
   from /home/garo/miniconda3/lib/python3.9/site-packages/lib/~kgconfig
  Moving to /home/garo/miniconda3/lib/python3.9/site-packages/lib64/
   from /home/garo/miniconda3/lib/python3.9/site-packages/~ib64
  Moving to /home/garo/miniconda3/lib/python3.9/site-packages/libnetworkit.so
   from /tmp/pip-uninstall-9gc5bcua/libnetworkit.so
  Moving to /home/garo/miniconda3/lib/python3.9/site-packages/networkit-10.0.dist-info/
   from /home/garo/miniconda3/lib/python3.9/site-packages/~etworkit-10.0.dist-info
  Moving to /home/garo/miniconda3/lib/python3.9/site-packages/networkit.libs/
   from /home/garo/miniconda3/lib/python3.9/site-packages/~etworkit.libs
  Moving to /home/garo/miniconda3/lib/python3.9/site-packages/networkit/
   from /home/garo/miniconda3/lib/python3.9/site-packages/~etworkit
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> networkit

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by fabratu** [comment]
My bad. Only mentioned package `gcc-9`. This does not install the C++ compiler, therefore the `is not a full path ...` error.
```
sudo apt-get install g++-9
```
Try if that helps.
