### ISSUE TITLE
Python 3.11 requires cython to install networkit, but this is not marked as depedency

### ISSUE THREAD

**Issue by TNieuwdorp** [networkit/networkit#1020]
Poetry fails to install networkit (at least 9.1.1) because it requires cython to install. However cython is not marked as a dependency for networkit, causing the install to fail.

```
  • Installing networkit (9.1.1): Failed

  CalledProcessError

  Command '['/home/as2-streaming-user/delvi-core/python/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/home/as2-streaming-user/delvi-core/python/.venv', '--no-deps', '/home/as2-streaming-user/.cache/pypoetry/artifacts/de/cb/53/f9128519ee2c5a111598c9b3398ca1a5b0746113f9e904dcb85c39b315/networkit-9.1.1.tar.gz']' returned non-zero exit status 1.

  at /opt/pyenv/versions/3.11.0/lib/python3.11/subprocess.py:569 in run
       565│             # We don't call process.wait() as .__exit__ does that for us.
       566│             raise
       567│         retcode = process.poll()
       568│         if check and retcode:
    →  569│             raise CalledProcessError(retcode, process.args,
       570│                                      output=stdout, stderr=stderr)
       571│     return CompletedProcess(process.args, retcode, stdout, stderr)
       572│ 
       573│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/home/as2-streaming-user/delvi-core/python/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/home/as2-streaming-user/delvi-core/python/.venv', '--no-deps', '/home/as2-streaming-user/.cache/pypoetry/artifacts/de/cb/53/f9128519ee2c5a111598c9b3398ca1a5b0746113f9e904dcb85c39b315/networkit-9.1.1.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/as2-streaming-user/.cache/pypoetry/artifacts/de/cb/53/f9128519ee2c5a111598c9b3398ca1a5b0746113f9e904dcb85c39b315/networkit-9.1.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [21 lines of output]
        Traceback (most recent call last):
          File "/home/as2-streaming-user/delvi-core/python/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
            main()
          File "/home/as2-streaming-user/delvi-core/python/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/home/as2-streaming-user/delvi-core/python/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-7_ofbwl0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-7_ofbwl0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-7_ofbwl0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
            self).run_setup(setup_script=setup_script)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-7_ofbwl0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 7, in <module>
        ModuleNotFoundError: No module named 'Cython'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  

  at /opt/poetry/venv/lib/python3.11/site-packages/poetry/utils/env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│ 
      1478│         return decode(output)
      1479│ 
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /home/as2-streaming-user/.cache/pypoetry/artifacts/de/cb/53/f9128519ee2c5a111598c9b3398ca1a5b0746113f9e904dcb85c39b315/networkit-9.1.1.tar.gz

  at /opt/poetry/venv/lib/python3.11/site-packages/poetry/utils/pip.py:51 in pip_install
       47│ 
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│ 
```

Normally I'd manually install cython and then networkit, but in my situation I can only make use of the poetry install command. I tried to add cython to the build-system.requires in the pyproject.toml file, but to no avail...
Do you guys see anything I missed?

**Comment by TNieuwdorp** [comment]
Additional info: I noticed that after attempting this, installing cython and networkit==9.1.1 with pip does work, and then running poetry install again makes it succeed... Is there a difference between installing through pip and installing through poetry? 
Note: this does not solve it for me since I rely on a successful poetry install

**Comment by fabratu** [comment]
Hi, thanks for reaching out!

Officially installing through poetry is not yet fully supported (it works though). Currently you need to add Cython to the pyproject.toml file. Also see here for a discussion about the topic: https://github.com/networkit/networkit/discussions/775

In principal installing via pip is not different from installing via poetry. However pip prefers installing wheels, so for most common combinations of OS / Python-version a pre-built package is installed. This eliminates the need for Cython. Since you are using Python 3.11, networkit 10.1 will be the first version with a wheel-package for 3.11.

**Comment by TNieuwdorp** [comment]
Thanks for your clear explanation! I'll see if I can ask the devs of my dependency that uses networkit to update it to 10.1.

Unfortunately in my case, when adding Cython to the dependencies in pyproject.toml, poetry decides Cython should get installed after networkit, which doesn't fix the problem...
