### ISSUE TITLE
networkit.community.SpectralPartitioner not working for simple generated networkit graphs.

### ISSUE THREAD

**Issue by Sonalj96** [networkit/networkit#1100]
I am unsure what is going wrong here and why I am getting this error. I have tried 1) changing the number of partitions 2) setting the balance to 'True' and 3) checking whether the graph is 0 indexed, but still no luck. On the other hand, Louvain (networkit.community.PLM), Leiden(networkit.community.ParallelLeiden), and Label propagation (networkit.community.PLP) methods are working fine on the same generated graph. 

```
import networkit as nk
from networkit import *

G = generators.ClusteredRandomGraphGenerator(1e2,5,0.2,0.8).generate()
overview(G)
Network Properties:
nodes, edges            100, 3371
directed?            False
weighted?            False
isolated nodes            0
self-loops            0
density                0.681010
clustering coefficient        0.664382
min/max/avg degree        58, 78, 67.420000
degree assortativity        -0.056738
number of connected components    1
size of largest component    100 (100.00 %)

spectralCommunities = nk.community.detectCommunities(G, algo=nk.community.SpectralPartitioner(G, 10, False))

/home/.conda/envs/gtcommunitydetection/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/.conda/envs/gtcommunitydetection/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "networkit/community.pyx", line 1651, in networkit.community.detectCommunities
  File "networkit/community.pyx", line 2185, in networkit.community.SpectralPartitioner.run
  File "networkit/community.pyx", line 2144, in networkit.community.SpectralPartitioner._bisect
  File "networkit/community.pyx", line 2153, in networkit.community.SpectralPartitioner._bisect
  File "networkit/community.pyx", line 2080, in networkit.community.SpectralPartitioner._trisect
  File "networkit/community.pyx", line 2060, in networkit.community.SpectralPartitioner._getQuantiles
IndexError: list index out of range
```

**Comment by fabratu** [comment]
Thanks for posting the issue!

We are currently working on a fix. It seems, that this particular partitioner (rather old and previously untested code) returns nothing (hence the out of range error).
