### ISSUE TITLE
Some Python tests fail for higher number of threads

### ISSUE THREAD

**Issue by fabratu** [networkit/networkit#1172]
When executed with 48 threads, several unittests for the Python interface fail:

```
======================================================================
FAIL: testApproxElectricalCloseness (test_centrality.TestCentrality.testApproxElectricalCloseness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brandtfa/scripts/test/test_centrality.py", line 55, in testApproxElectricalCloseness
    self.assertLessEqual(abs(apx[u] - pinv[u]), eps)
AssertionError: 0.11044452053538456 not less than or equal to 0.1

======================================================================
FAIL: testApproxSpanningEdge (test_centrality.TestCentrality.testApproxSpanningEdge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brandtfa/scripts/test/test_centrality.py", line 68, in testApproxSpanningEdge
    self.assertLessEqual(abs(apxScore - exactScore), 2*eps)
AssertionError: 0.24007940334904146 not less than or equal to 0.2

======================================================================
FAIL: testForest (test_centrality.TestCentrality.testForest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brandtfa/scripts/test/test_centrality.py", line 292, in testForest
    self.assertLessEqual(abs(apx - exact), eps)
AssertionError: 0.06750794287494666 not less than or equal to 0.05

----------------------------------------------------------------------
```

Reducing the number of threads mitigates this problem.

**Comment by domischweisgut** [comment]
Fixed via PR #1411
