### ISSUE TITLE
Large RMAT Graph Generation Error for Large Size

### ISSUE THREAD

**Issue by kaanolgu** [networkit/networkit#1261]
Hi, 
I was trying to build rmat graphs via 

```
    S = int(sys.argv[2]) # scale factor
    E = int(sys.argv[3]) # edge factor


    # Benchmark Parameters 
    A = 0.57
    B = 0.19
    C = 0.19
    D = 1-(A+B+C) 

    # Generate Graph
    rmat = nk.generators.RmatGenerator(S, E, A, B, C, D,False,0)
    rmatG = rmat.generate()
    
    print(rmatG.numberOfNodes(), rmatG.numberOfEdges(), rmatG.isDirected())
```
It worked for scale factor <25
I am getting error message for S=28, E=16 after running for a long time, slurm killed the job but didn't give any error messages so I would think it is a memory issue. Is there a way to generate large size RMAT graphs faster or OpenMP involved with the CPP version?

**Comment by kaanolgu** [comment]
Ok found the problem it was about the memory size so now I am able to generate larger datasets upto Rmat30-16 but the problem is with rmat31-16 I am getting this error message : 
```
Traceback (most recent call last):
  File "/scratch/scripts/genGraph.py", line 56, in <module>
    rmatG = rmat.generate()
            ^^^^^^^^^^^^^^^
  File "networkit/generators.pyx", line 74, in networkit.generators.StaticGraphGenerator.generate
RuntimeError: Error, shall delete more nodes than the graph originally has
```
and with rmat32-16 this error message :
```
/var/spool/slurmd/job16306672/slurm_script: line 12: 645029 Segmentation fault      (core dumped) python genGraph.py rmat 32 16
```

I think the limitation comes from using int datatype rather than uint32 ? Is there a way to use larger datatypes like uint64_t too ? 

Thanks

**Comment by fabratu** [comment]
The [fix](https://github.com/networkit/networkit/pull/1268) seems to work, however I can not verify it easily. Our local cluster (1.5TB RAM) runs OOM for rmat32-16. However, for both 31-16 and 32-16, your issues, namely the runtime error and segmentation fault, do not occur anymore.

If it is possible, maybe you can try to validate the fix on your system?

**Comment by fabratu** [comment]
Closing this issue - feel free to reopen it if the error reoccurs.
