### ISSUE TITLE
networkit 8.0 build failure

### ISSUE THREAD

**Issue by chenrui333** [networkit/networkit#644]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>test failure</summary>

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/networkit/8.0/libexec/lib/python3.9/site-packages/networkit/__init__.py", line 53, in <module>
    from . import community
  File "networkit/community.pyx", line 35, in init networkit.community
ImportError: dlopen(/usr/local/Cellar/networkit/8.0/libexec/lib/python3.9/site-packages/networkit/centrality.cpython-39-darwin.so, 2): Symbol not found: __ZN9NetworKit20TopHarmonicCloseness13topkNodesListEb
  Referenced from: /usr/local/Cellar/networkit/8.0/libexec/lib/python3.9/site-packages/networkit/centrality.cpython-39-darwin.so
  Expected in: flat namespace
 in /usr/local/Cellar/networkit/8.0/libexec/lib/python3.9/site-packages/networkit/centrality.cpython-39-darwin.so
Error: networkit: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/opt/python@3.9/bin/python3 -c import\ networkit\ as\ nk
G\ =\ nk.graph.Graph(3)
G.addEdge(0,1)
G.addEdge(1,2)
G.addEdge(2,0)
assert\ G.degree(0)\ ==\ 2
assert\ G.degree(1)\ ==\ 2
assert\ G.degree(2)\ ==\ 2
```

</details>

Full build log is here, https://github.com/Homebrew/homebrew-core/runs/1578257332
relates to https://github.com/Homebrew/homebrew-core/pull/67184

**Comment by angriman** [comment]
Probably @fabratu knows this better than me.

**Comment by fabratu** [comment]
Thanks @chenrui333 for bringing this up and taking care of the brew-update. I am tracking now the process of Homebrew/homebrew-core#67184. Seems, that the error above, is gone by now and was most likely introduced by bumping networkit package but not the dependencies (e.g. `libnetworkit`). Will therefore close this issue.
