### ISSUE TITLE
EdmondsKarp is missing .run() method

### ISSUE THREAD

**Issue by AndrewHannigan** [networkit/networkit#721]
EdmondsKarp is missing the `.run()` method, but it also complains that the .run() method needs to be called before `getMaxFlow()` can be called.

```
>>> g = nk.generators.ErdosRenyiGenerator(nNodes=1000, prob=0.2, directed=True).generate()
>>> gw = nk.graphtools.toWeighted(g)
>>> ek = nk.flow.EdmondsKarp(graph=gw, source=100_000_000, sink=200_000_000)
>>> ek.run()

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-9ec6715874fc>", line 1, in <module>
    ek.run()
AttributeError: 'networkit.flow.EdmondsKarp' object has no attribute 'run'
```

Calling getMaxFlow without run first yields SIGSEGV
```
>>> ek.getMaxFlow()

terminate called after throwing an instance of 'std::runtime_error'
  what():  Error, run must be called first
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by angriman** [comment]
@AndrewHannigan we merged a fix for this issue, thanks for pointing this out.
