### ISSUE TITLE
Issue using EdgeListReader with firstNode > 0 and continuous=False

### ISSUE THREAD

**Issue by AndrewHannigan** [networkit/networkit#728]
example.edgelist:
```
5,10,1.0
```

Problem:
```{python}
# Works fine with continuous=False
br = nk.graphio.EdgeListReader(separator=",", firstNode=0, continuous=False, directed=True)
g = br.read("example.edgelist") 

# Works fine with firstNode=5
br = nk.graphio.EdgeListReader(separator=",", firstNode=5, continuous=True, directed=True)
g = br.read("example.edgelist") 

# Breaks with continous=False and firstNode=5
br = nk.graphio.EdgeListReader(separator=",", firstNode=5, continuous=False, directed=True)
g = br.read("example.edgelist") 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-34-ac74bf995011>", line 1, in <module>
    g = br.read("/opt/project/multihop/testing/example.edgelist")
  File "networkit/graphio.pyx", line 70, in networkit.graphio.GraphReader.read
RuntimeError: vector<bool>::_M_fill_insert
```

Use case:
Node ids in my actual edgelist are generated via a hashing function.  So they neither start at 0 nor are they continuous.

**Comment by michitux** [comment]
Setting `firstNode` to 0 is correct here, `continuous = False` means that new node ids starting at 0 are assigned. There is a bug in NetworKit when you set `firstNode > 0` and `continuous = False`, see also #725 and #727.
